# Generated by Django 4.0.5 on 2022-06-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
