# Generated by Django 4.0.5 on 2022-06-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
